name: Clojure CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install dependencies
      run: lein deps
    - name: Kibit static code analysis
      run: lein kibit
    - name: Run tests
      run: lein test
    - name: Check coverage
      run: lein cloverage --fail-threshold 25
    - name: Coverage reporting
      uses: romeovs/lcov-reporter-action@v0.2.16
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        lcov-file: ./coverage/lcov.info
