name: slack-pr-notification
on:
  pull_request:
    branches: [ master ]

jobs:
  slackNotification:
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Read file contents
        id: read_file
        uses: andstor/file-reader-action@v1
        with:
          path: "LICENSE"
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_COLOR: ${{ job.status }} # or a specific color like 'good' or '#ff00ff'
          SLACK_ICON_EMOJI: ':bell:'
          SLACK_USERNAME: 'PR notification action'
          MSG_MINIMAL: 'event'
          SLACK_TITLE: 'Release notes'
          SLACK_MESSAGE: ${{ steps.read_file.outputs.contents }}
